# Generated by Django 5.1.7 on 2025-04-08 03:01

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0005_veterinaria_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaria',
            name='horario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='servicios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('spa', 'Spa'), ('consulta', 'Consulta veterinaria'), ('cirugia', 'Cirugía'), ('farmacia', 'Farmacia'), ('accesorios', 'Venta de accesorios'), ('comida', 'Venta de comida'), ('domicilio', 'Servicio a domicilio'), ('pension', 'Pensión'), ('esterilizacion', 'Esterilización')], max_length=80),
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='veterinarias.veterinaria')),
            ],
            options={
                'unique_together': {('veterinaria', 'dia')},
            },
        ),
    ]
