# Generated by Django 5.1.7 on 2025-04-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0006_alter_veterinaria_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinaria',
            name='horario',
        ),
    ]
