# Generated by Django 5.1.7 on 2025-04-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0007_remove_veterinaria_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarioatencion',
            old_name='hora_cierre',
            new_name='hora_fin',
        ),
        migrations.RenameField(
            model_name='horarioatencion',
            old_name='hora_apertura',
            new_name='hora_inicio',
        ),
        migrations.AlterUniqueTogether(
            name='horarioatencion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='horario',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='dia',
            field=models.CharField(max_length=10),
        ),
    ]
