# Generated by Django 5.1.7 on 2025-04-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0008_rename_hora_cierre_horarioatencion_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaria',
            name='horario',
            field=models.JSONField(default={'domingo': {'apertura': 'cerrado', 'cierre': 'cerrado'}, 'jueves': {'apertura': '08:00', 'cierre': '18:00'}, 'lunes': {'apertura': '08:00', 'cierre': '18:00'}, 'martes': {'apertura': '08:00', 'cierre': '18:00'}, 'miércoles': {'apertura': '08:00', 'cierre': '18:00'}, 'sábado': {'apertura': '10:00', 'cierre': '14:00'}, 'viernes': {'apertura': '08:00', 'cierre': '18:00'}}),
        ),
    ]
