# Generated by Django 5.1.7 on 2025-04-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0009_alter_veterinaria_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioatencion',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horarioatencion',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horarioatencion',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='horarioatencion',
            name='veterinaria',
        ),
        migrations.RemoveField(
            model_name='veterinaria',
            name='horario',
        ),
    ]
